### PR TITLE
[Fix #165] Fix a false positive for `Performance/Sum`

### LINKED ISSUE #165: Autocorrect for Performance/Sum drops initial value if it is not a number literal
When autocorrecting, the new Performance/Sum cop should take the initial value provided to `inject` or `reduce` and pass that as the first argument to `sum`, even when it is not a number literal.

This is corrected correctly:

```ruby
foo.inject(23, :+)
```

But this is not:

```ruby
foo.inject(bar, :+)
```
## Expected behavior

The code
```ruby
foo.inject(bar, :+)
```
should be corrected to 
```ruby
foo.sum(bar)
```

Also, more complex code like the following real-world example:
```ruby
paid_bills.reduce(AmountWithVAT.new, :+)
```
should be corrected to
```ruby
paid_bills.sum(AmountWithVAT.new)
```

## Actual behavior

The two examples given above are corrected to
```ruby
foo.sum
```
and
```ruby
paid_bills.sum
```

## Steps to reproduce the problem

Let `rubocop-performance` autocorrect the examples given above

## RuboCop version

```
0.90.0 (using Parser 2.7.1.4, rubocop-ast 0.3.0, running on ruby 2.7.1 x86_64-linux)
```

`rubocop-performance` is at version 1.8.0.

### PR DESCRIPTION
**Pull request by koic**
Fixes #165.

This PR fixes a false positive for `Performance/Sum` when using initial value argument is a variable.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop-performance/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop-performance/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/performance/sum.rb [hunk 1]
```diff
@@ -98,7 +98,7 @@ def build_good_method(init)
 
           unless init.empty?
             init = init.first
-            good_method += "(#{init.source})" if init.source.to_i != 0
+            good_method += "(#{init.source})" unless init.int_type? && init.source.to_i.zero?
```
Comment (marcandre) [inline lib/rubocop/cop/performance/sum.rb:101]: `init.source.to_i.zero?` => `init.value.zero?`

Comment (koic) [reply lib/rubocop/cop/performance/sum.rb]: It's definitely simple. Thank you for your review!

**Review by marcandre — APPROVED** [review]

**Comment by mvz** [comment]
Thanks, @koic!

**Comment by koic** [comment]
@mvz You are welcome. Thank you for your feedback!
