### PR TITLE
[Fix #147] Fix an error for `Performance/AncestorsInclude`

### LINKED ISSUE #147: Performance/AncestorsInclude with auto correct raises error
Performance/AncestorsInclude with auto correct raises error

## Steps to reproduce the problem

Add `<file>` with text `ancestors.include?(SomeClass)`
Check it with `rubocop  <file> --auto-correct --debug`

Output includes error:
```
An error occurred while Performance/AncestorsInclude cop was inspecting <file>:1:0.
undefined method `source' for nil:NilClass
~/rubocop-performance-1.7.0/lib/rubocop/cop/performance/ancestors_include.rb:38:in `block (2 levels) in autocorrect'
~/rubocop-0.87.1/lib/rubocop/cop/cop.rb:134:in `block in emulate_v0_callsequence'
~/rubocop-0.87.1/lib/rubocop/cop/cop.rb:154:in `suppress_clobbering'
~/rubocop-0.87.1/lib/rubocop/cop/cop.rb:133:in `emulate_v0_callsequence'
~/rubocop-0.87.1/lib/rubocop/cop/cop.rb:34:in `block in add_offense'
~/rubocop-0.87.1/lib/rubocop/cop/base.rb:302:in `correct'
~/rubocop-0.87.1/lib/rubocop/cop/base.rb:115:in `add_offense'
~/rubocop-0.87.1/lib/rubocop/cop/cop.rb:33:in `add_offense'
```

## RuboCop version

```
rubocop -V
0.87.1 (using Parser 2.7.1.4, rubocop-ast 0.1.0, running on ruby 2.6.6 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #147.

This PR fixes an error for `Performance/AncestorsInclude` when using `ancestors.include?` without receiver.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop-performance/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop-performance/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/performance/ancestors_include.rb [hunk 1]
```diff
@@ -35,7 +35,9 @@ def on_send(node)
         def autocorrect(node)
           ancestors_include_candidate?(node) do |subclass, superclass|
             lambda do |corrector|
-              corrector.replace(node, "#{subclass.source} <= #{superclass.source}")
+              subclass_source = subclass ? subclass.source : 'self.class'
```
Comment (eugeneius) [inline lib/rubocop/cop/performance/ancestors_include.rb:38]: The receiver of `ancestors` is already a class.

```suggestion
              subclass_source = subclass ? subclass.source : 'self'
```

File: spec/rubocop/cop/performance/ancestors_include_spec.rb [hunk 2]
```diff
@@ -14,6 +14,17 @@
...
   end
 
+  it 'registers an offense and corrects when using `ancestors.include?` without receiver' do
+    expect_offense(<<~RUBY)
+      ancestors.include?(Klass)
+      ^^^^^^^^^^^^^^^^^^ Use `<=` instead of `ancestors.include?`.
+    RUBY
+
+    expect_correction(<<~RUBY)
+      self.class <= Klass
```
Comment (eugeneius) [inline spec/rubocop/cop/performance/ancestors_include_spec.rb:24]:
```suggestion
      self <= Klass
```

File: lib/rubocop/cop/performance/ancestors_include.rb (hunk 1 above)
Comment (koic) [reply lib/rubocop/cop/performance/ancestors_include.rb]: Ah...sure 💦  I updated it. Thank you for your review!
